@echo off
echo Running migrations...
php artisan migrate:fresh --force
echo Clearing config cache...
php artisan optimize:clear
echo Running custom data migration script...
php artisan migrate:mongo
echo Done!
